# $FreeBSD$

PORTNAME=	nss_ndb
DISTVERSIONPREFIX=v
DISTVERSION=	1.0.22-dev
CATEGORIES=	sysutils security

MAINTAINER=	pen@lysator.liu.se
COMMENT=	DB-based nsswitch backend for passwd & groups

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

OPTIONS_DEFINE=	DB

DB_DESC=	Build with modern Berkeley DB library

DB_CONFIGURE_WITH=db

USE_GITHUB=	yes
GH_ACCOUNT=	ptrrkssn

GNU_CONFIGURE=	yes

PLIST_FILES=	lib/nss_ndb.so.1 lib/nss_ndb.so.1.0.22-dev sbin/makendb

.include <bsd.port.mk>
